{% set name = "itt-python" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/oleksandr-pavlyk/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: 1d350bf062a9e960c637b7277d4dcd372b02e95b5c54b56709b456d7a6f62f65

build:
  number: 1
  skip: True  # [not (linux64 or win64)]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - ittapi
  run:
    - python

test:
  imports:
    - itt
  source_files:
    - itt/tests
  commands:
    - pytest -v itt/tests
  requires:
    - pytest

about:
  home: https://github.com/oleksandr-pavlyk/itt-python
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: 'Python bindings to Intel® Instrumentation and Tracing Technology (ITT) APIs'
  description: |
    This package exposes some limited features of the ITT API in Python to help focus analysis in e.g. Intel® VTune.
    Right now it only has the collection and control API and some of the user task API.
  doc_url: https://github.com/oleksandr-pavlyk/itt-python
  dev_url: https://github.com/oleksandr-pavlyk/itt-python

extra:
  recipe-maintainers:
    - oleksandr-pavlyk
